# Recommandation avec cold start

In [1]:
import pandas as pd

import seaborn as sns

from deep_implicit_feedback_recsys import *

from cold_star_recommender import *

from recommender_evaluation import *

Using TensorFlow backend.

In [2]:
def normalized_results(df, recommender_type):
    df['average_reward_normalized_max'] = df['average_reward'] / df['max_price']
    df['average_reward_normalized_mean'] = df['average_reward'] / df['mean_price']
    df['recommendation'] = recommender_type
    return df

In [3]:
n_loop = 5
n_pred = 100
online_batch_size = n_pred // 10
n_hidden = 1
hidden_size = 128
dropout = 0.1
l2_reg = 0

## Mesures d'Ã©chantillon

### Implicit Recommender Simple, hors ligne

In [4]:
%%time
ImplicitRecommenderSimple_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                      ImplicitRecommenderClass=ImplicitRecommenderSimple, 
                                                                      n_loop=n_loop, n_pred=n_pred,
                                                                      n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                      dropout=dropout, l2_reg=l2_reg)

CPU times: user 10.5 s, sys: 194 ms, total: 10.7 s
Wall time: 18.2 s

In [5]:
ImplicitRecommenderSimple_df_normalized = normalized_results(ImplicitRecommenderSimple_df, 'Simple, hors ligne')
ImplicitRecommenderSimple_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,957.501488,65.046223,290.835379,0.35,0.303744,4.471211,"Simple, hors ligne"
1,981.588102,68.029027,97.843225,0.27,0.099678,1.438257,"Simple, hors ligne"
2,979.554251,73.144957,85.296670,0.30,0.087077,1.166132,"Simple, hors ligne"
3,968.632593,75.709300,164.002453,0.25,0.169313,2.166213,"Simple, hors ligne"
4,987.989182,68.602978,298.738453,0.33,0.302370,4.354599,"Simple, hors ligne"

### Implicit Recommender Simple, en ligne

In [6]:
%%time
ImplicitRecommenderSimple_online_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=1,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 11.3 s, sys: 192 ms, total: 11.5 s
Wall time: 19.5 s

In [7]:
ImplicitRecommenderSimple_online_df_normalized = normalized_results(ImplicitRecommenderSimple_online_df, 'Simple, en ligne')
ImplicitRecommenderSimple_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,977.192071,75.965122,384.894125,0.46,0.393878,5.066722,"Simple, en ligne"
1,994.530833,91.630753,88.213162,0.22,0.088698,0.962703,"Simple, en ligne"
2,937.320573,57.358152,76.157057,0.28,0.081250,1.327746,"Simple, en ligne"
3,999.739352,69.952032,91.818967,0.21,0.091843,1.312599,"Simple, en ligne"
4,994.188347,74.488222,189.829776,0.24,0.190939,2.548454,"Simple, en ligne"

### Implicit Recommender Simple, en ligne version batch

In [8]:
%%time
ImplicitRecommenderSimple_online_batch_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=online_batch_size,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 12.6 s, sys: 210 ms, total: 12.8 s
Wall time: 19 s

In [9]:
ImplicitRecommenderSimple_online_batch_df_normalized = normalized_results(ImplicitRecommenderSimple_online_batch_df, 'Simple, en ligne (batch)')
ImplicitRecommenderSimple_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,959.815157,54.513538,193.200399,0.29,0.201289,3.544081,"Simple, en ligne (batch)"
1,988.170701,69.709950,85.328245,0.29,0.086350,1.224047,"Simple, en ligne (batch)"
2,990.254421,70.500940,225.222063,0.28,0.227439,3.194597,"Simple, en ligne (batch)"
3,958.280863,68.171923,57.880358,0.24,0.060400,0.849035,"Simple, en ligne (batch)"
4,934.789054,58.209704,81.056817,0.28,0.086711,1.392497,"Simple, en ligne (batch)"

### Implicit Recommender avec nuls sans indicateur, hors ligne

In [10]:
%%time
ImplicitRecommenderWithNull_no_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator, 
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 14.8 s, sys: 313 ms, total: 15.1 s
Wall time: 19.8 s

In [11]:
ImplicitRecommenderWithNull_no_indicator_df_normalized = normalized_results(ImplicitRecommenderWithNull_no_indicator_df, 'Null, hors ligne')
ImplicitRecommenderWithNull_no_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,991.531521,83.304838,187.778854,0.26,0.189383,2.254117,"Null, hors ligne"
1,983.963959,62.844444,94.549389,0.33,0.096090,1.504499,"Null, hors ligne"
2,988.292452,61.838665,110.024446,0.43,0.111328,1.779218,"Null, hors ligne"
3,999.173217,68.195340,95.247931,0.38,0.095327,1.396693,"Null, hors ligne"
4,981.937681,63.439576,45.864059,0.23,0.046708,0.722957,"Null, hors ligne"

### Implicit Recommender avec nuls sans indicateur, en ligne

In [12]:
%%time
ImplicitRecommenderWithNull_no_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 16 s, sys: 264 ms, total: 16.3 s
Wall time: 20.9 s

In [13]:
ImplicitRecommenderWithNull_no_indicator_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_no_indicator_online_df,
                                                                                   'Null, en ligne')
ImplicitRecommenderWithNull_no_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,972.133029,78.318868,193.041968,0.45,0.198576,2.464821,"Null, en ligne"
1,993.349456,63.478398,91.553596,0.26,0.092167,1.442280,"Null, en ligne"
2,997.739661,68.853379,180.846467,0.28,0.181256,2.626545,"Null, en ligne"
3,998.836160,70.074970,222.922083,0.26,0.223182,3.181194,"Null, en ligne"
4,973.350195,77.776741,98.734418,0.31,0.101438,1.269459,"Null, en ligne"

### Implicit Recommender avec nuls sans indicateur, en ligne version batch

In [14]:
%%time
ImplicitRecommenderWithNull_no_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 17.7 s, sys: 311 ms, total: 18 s
Wall time: 22.3 s

In [15]:
ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_no_indicator_online_batch_df, 'Null, en ligne (batch)')
ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,979.964238,72.872595,267.841789,0.32,0.273318,3.675480,"Null, en ligne (batch)"
1,989.560140,77.677254,276.498180,0.34,0.279415,3.559577,"Null, en ligne (batch)"
2,992.328975,71.791592,87.194658,0.26,0.087869,1.214552,"Null, en ligne (batch)"
3,996.023316,72.839716,199.149641,0.25,0.199945,2.734080,"Null, en ligne (batch)"
4,977.677444,63.358547,66.764735,0.31,0.068289,1.053761,"Null, en ligne (batch)"

### Implicit Recommender avec nuls et indicateur binaire, hors ligne

In [16]:
%%time
ImplicitRecommenderWithNull_binary_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 19.3 s, sys: 306 ms, total: 19.6 s
Wall time: 23.8 s

In [17]:
ImplicitRecommenderWithNull_binary_indicator_df_normalized = normalized_results(ImplicitRecommenderWithNull_binary_indicator_df,
                                                                                'Null binaire, hors ligne')
ImplicitRecommenderWithNull_binary_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,990.332115,72.301398,216.432377,0.25,0.218545,2.993474,"Null binaire, hors ligne"
1,941.308341,60.270555,101.257124,0.36,0.107571,1.680043,"Null binaire, hors ligne"
2,994.312979,73.489941,93.814414,0.25,0.094351,1.276561,"Null binaire, hors ligne"
3,927.739880,67.676181,183.219197,0.32,0.197490,2.707292,"Null binaire, hors ligne"
4,998.800905,76.907352,364.113517,0.42,0.364551,4.734444,"Null binaire, hors ligne"

### Implicit Recommender avec nuls et indicateur binaire, en ligne

In [18]:
%%time
ImplicitRecommenderWithNull_binary_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 20.7 s, sys: 335 ms, total: 21.1 s
Wall time: 25.4 s

In [19]:
ImplicitRecommenderWithNull_binary_indicator_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_binary_indicator_online_df,
                                                                                       'Null binaire, en ligne')
ImplicitRecommenderWithNull_binary_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,999.727823,64.991177,232.070575,0.29,0.232134,3.570801,"Null binaire, en ligne"
1,991.323423,60.864597,176.101083,0.25,0.177642,2.893325,"Null binaire, en ligne"
2,986.954566,76.446328,306.126107,0.38,0.310172,4.004458,"Null binaire, en ligne"
3,959.702744,63.530957,79.097385,0.24,0.082419,1.245021,"Null binaire, en ligne"
4,943.811491,73.261629,160.596587,0.24,0.170157,2.192097,"Null binaire, en ligne"

### Implicit Recommender avec nuls et indicateur binaire, en ligne version batch

In [20]:
%%time
ImplicitRecommenderWithNull_binary_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.7 s, sys: 305 ms, total: 22 s
Wall time: 26.2 s

In [21]:
ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_binary_indicator_online_batch_df, 'Null binaire, en ligne (batch)')
ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,953.066911,73.315213,94.350118,0.28,0.098996,1.286911,"Null binaire, en ligne (batch)"
1,977.852381,68.811445,221.590238,0.29,0.226609,3.220253,"Null binaire, en ligne (batch)"
2,985.716650,61.119553,74.236273,0.28,0.075312,1.214608,"Null binaire, en ligne (batch)"
3,925.122380,66.763892,79.883387,0.36,0.086349,1.196506,"Null binaire, en ligne (batch)"
4,992.895224,75.938972,69.064783,0.39,0.069559,0.909477,"Null binaire, en ligne (batch)"

### Implicit Recommender avec nuls et indicateur special, hors ligne

In [22]:
%%time
ImplicitRecommenderWithNull_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 24 s, sys: 348 ms, total: 24.3 s
Wall time: 28.6 s

In [23]:
ImplicitRecommenderWithNull_df_normalized = normalized_results(ImplicitRecommenderWithNull_df, 'Null special, hors ligne')
ImplicitRecommenderWithNull_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,868.125406,61.065511,113.260045,0.29,0.130465,1.854730,"Null special, hors ligne"
1,999.222496,73.835788,260.945585,0.33,0.261149,3.534134,"Null special, hors ligne"
2,997.450520,70.529940,86.219955,0.24,0.086440,1.222459,"Null special, hors ligne"
3,992.762949,76.668829,214.881874,0.24,0.216448,2.802728,"Null special, hors ligne"
4,779.079450,57.434848,217.334812,0.39,0.278964,3.784023,"Null special, hors ligne"

### Implicit Recommender avec nuls et indicateur special, en ligne

In [24]:
%%time
ImplicitRecommenderWithNull_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 25.7 s, sys: 315 ms, total: 26 s
Wall time: 30.7 s

In [25]:
ImplicitRecommenderWithNull_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_online_df, 'Null special, en ligne')
ImplicitRecommenderWithNull_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,998.272537,76.614346,145.158369,0.37,0.145410,1.894663,"Null special, en ligne"
1,879.509723,69.946620,233.289197,0.36,0.265249,3.335246,"Null special, en ligne"
2,967.005254,68.263401,97.530080,0.36,0.100858,1.428732,"Null special, en ligne"
3,983.441069,76.248542,262.870897,0.32,0.267297,3.447553,"Null special, en ligne"
4,914.822166,64.095356,61.019819,0.33,0.066701,0.952016,"Null special, en ligne"

### Implicit Recommender avec nuls et indicateur special, en ligne version batch

In [26]:
%%time
ImplicitRecommenderWithNull_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 26.9 s, sys: 369 ms, total: 27.2 s
Wall time: 33 s

In [27]:
ImplicitRecommenderWithNull_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_online_batch_df, 'Null special, en ligne (batch)')
ImplicitRecommenderWithNull_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,998.092731,82.972758,239.659863,0.28,0.240118,2.888416,"Null special, en ligne (batch)"
1,960.271628,74.016166,209.235603,0.28,0.217892,2.826891,"Null special, en ligne (batch)"
2,982.550108,62.655088,89.993400,0.24,0.091592,1.436330,"Null special, en ligne (batch)"
3,972.313881,70.840941,56.979804,0.29,0.058602,0.804334,"Null special, en ligne (batch)"
4,979.749411,79.510398,326.450532,0.39,0.333198,4.105759,"Null special, en ligne (batch)"

### Fully Implicit Recommender Simple, hors ligne

In [28]:
%%time
FullyImplicitRecommenderSimple_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                      ImplicitRecommenderClass=ImplicitRecommenderSimple, 
                                                                      n_loop=n_loop, n_pred=n_pred,
                                                                      n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                      dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.74 s, sys: 111 ms, total: 9.85 s
Wall time: 19.6 s

In [29]:
FullyImplicitRecommenderSimple_df_normalized = normalized_results(FullyImplicitRecommenderSimple_df, 'Fully Implicit Simple, hors ligne')
FullyImplicitRecommenderSimple_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,950.150747,63.568003,152.168639,0.27,0.160152,2.393793,"Fully Implicit Simple, hors ligne"
1,962.326573,68.114692,165.488417,0.26,0.171967,2.429555,"Fully Implicit Simple, hors ligne"
2,889.104755,63.724489,173.111692,0.31,0.194703,2.716565,"Fully Implicit Simple, hors ligne"
3,991.306741,71.544209,155.621158,0.28,0.156986,2.175175,"Fully Implicit Simple, hors ligne"
4,850.979229,60.816818,113.179111,0.26,0.132999,1.860984,"Fully Implicit Simple, hors ligne"

### Fully Implicit Recommender Simple, en ligne

In [30]:
%%time
FullyImplicitRecommenderSimple_online_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=1,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.71 s, sys: 119 ms, total: 9.83 s
Wall time: 23.1 s

In [31]:
FullyImplicitRecommenderSimple_online_df_normalized = normalized_results(FullyImplicitRecommenderSimple_online_df, 'Fully Implicit Simple, en ligne')
FullyImplicitRecommenderSimple_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,959.474515,65.705092,154.905732,0.24,0.161449,2.357591,"Fully Implicit Simple, en ligne"
1,950.436916,72.720110,227.649210,0.36,0.239521,3.130485,"Fully Implicit Simple, en ligne"
2,985.646760,68.805331,156.601119,0.25,0.158882,2.276003,"Fully Implicit Simple, en ligne"
3,988.870952,67.000347,217.503122,0.32,0.219951,3.246298,"Fully Implicit Simple, en ligne"
4,935.834339,77.344298,173.836816,0.32,0.185756,2.247571,"Fully Implicit Simple, en ligne"

### Fully Implicit Recommender Simple, en ligne version batch

In [32]:
%%time
FullyImplicitRecommenderSimple_online_batch_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=online_batch_size,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.71 s, sys: 126 ms, total: 9.84 s
Wall time: 23.8 s

In [33]:
FullyImplicitRecommenderSimple_online_batch_df_normalized = normalized_results(FullyImplicitRecommenderSimple_online_batch_df, 'Fully Implicit Simple, en ligne (batch)')
FullyImplicitRecommenderSimple_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,998.504199,80.252536,158.047020,0.25,0.158284,1.969371,"Fully Implicit Simple, en ligne (batch)"
1,996.488399,70.024069,139.798602,0.32,0.140291,1.996436,"Fully Implicit Simple, en ligne (batch)"
2,955.206895,74.439463,197.028054,0.27,0.206267,2.646823,"Fully Implicit Simple, en ligne (batch)"
3,971.321945,71.434296,157.869031,0.35,0.162530,2.209989,"Fully Implicit Simple, en ligne (batch)"
4,934.333207,68.998876,91.414768,0.23,0.097840,1.324873,"Fully Implicit Simple, en ligne (batch)"

### Fully Implicit Recommender avec nuls sans indicateur, hors ligne

In [34]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator, 
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.86 s, sys: 95.4 ms, total: 9.95 s
Wall time: 19 s

In [35]:
FullyImplicitRecommenderWithNull_no_indicator_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_no_indicator_df, 'Fully Implicit Null, hors ligne')
FullyImplicitRecommenderWithNull_no_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,969.883366,83.056513,208.517637,0.38,0.214992,2.510551,"Fully Implicit Null, hors ligne"
1,996.903654,64.659044,143.215500,0.28,0.143660,2.214934,"Fully Implicit Null, hors ligne"
2,989.655259,64.252350,145.339676,0.28,0.146859,2.262013,"Fully Implicit Null, hors ligne"
3,957.146355,76.251372,192.562209,0.30,0.201184,2.525361,"Fully Implicit Null, hors ligne"
4,993.599723,68.213647,164.198005,0.38,0.165256,2.407114,"Fully Implicit Null, hors ligne"

### Fully Implicit Recommender avec nuls sans indicateur, en ligne

In [36]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.64 s, sys: 106 ms, total: 9.75 s
Wall time: 19.3 s

In [37]:
FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_no_indicator_online_df,
                                                                                   'Fully Implicit Null, en ligne')
FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,993.595705,50.621241,153.782829,0.35,0.154774,3.037911,"Fully Implicit Null, en ligne"
1,860.487529,64.916961,121.067610,0.28,0.140697,1.864961,"Fully Implicit Null, en ligne"
2,987.079198,63.818474,106.375339,0.20,0.107768,1.666842,"Fully Implicit Null, en ligne"
3,990.930055,73.839597,176.194770,0.32,0.177807,2.386183,"Fully Implicit Null, en ligne"
4,983.622889,65.391100,141.982891,0.25,0.144347,2.171288,"Fully Implicit Null, en ligne"

### Fully Implicit Recommender avec nuls sans indicateur, en ligne version batch

In [38]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.69 s, sys: 106 ms, total: 9.8 s
Wall time: 21.1 s

In [39]:
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_no_indicator_online_batch_df, 'Fully Implicit Null, en ligne (batch)')
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,994.981442,78.553480,197.507140,0.31,0.198503,2.514302,"Fully Implicit Null, en ligne (batch)"
1,959.185358,57.867595,172.462137,0.37,0.179801,2.980289,"Fully Implicit Null, en ligne (batch)"
2,937.375107,70.833227,176.726096,0.31,0.188533,2.494960,"Fully Implicit Null, en ligne (batch)"
3,953.220341,72.819148,191.638118,0.34,0.201043,2.631700,"Fully Implicit Null, en ligne (batch)"
4,991.120638,74.624090,155.396833,0.30,0.156789,2.082395,"Fully Implicit Null, en ligne (batch)"

### Fully Implicit Recommender avec nuls et indicateur binaire, hors ligne

In [40]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.43 s, sys: 86.5 ms, total: 9.51 s
Wall time: 14.4 s

In [41]:
FullyImplicitRecommenderWithNull_binary_indicator_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_df,
                                                                                'Fully Implicit Null binaire, hors ligne')
FullyImplicitRecommenderWithNull_binary_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,971.874884,59.441173,164.554740,0.27,0.169317,2.768363,"Fully Implicit Null binaire, hors ligne"
1,968.493006,60.815820,134.647095,0.28,0.139027,2.214014,"Fully Implicit Null binaire, hors ligne"
2,936.666984,73.088786,231.978479,0.38,0.247664,3.173927,"Fully Implicit Null binaire, hors ligne"
3,982.993037,63.919059,167.758590,0.34,0.170661,2.624547,"Fully Implicit Null binaire, hors ligne"
4,919.740390,73.153010,159.380249,0.25,0.173288,2.178724,"Fully Implicit Null binaire, hors ligne"

### Fully Implicit Recommender avec nuls et indicateur binaire, en ligne

In [42]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 8.8 s, sys: 94.7 ms, total: 8.9 s
Wall time: 13.9 s

In [43]:
FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_online_df,
                                                                                       'Fully Implicit Null binaire, en ligne')
FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,819.312462,68.896264,177.006442,0.34,0.216043,2.569173,"Fully Implicit Null binaire, en ligne"
1,967.826017,70.830495,195.146267,0.32,0.201634,2.755117,"Fully Implicit Null binaire, en ligne"
2,980.670583,82.150826,267.486155,0.39,0.272758,3.256037,"Fully Implicit Null binaire, en ligne"
3,980.627306,70.349798,167.719522,0.31,0.171033,2.384080,"Fully Implicit Null binaire, en ligne"
4,943.095296,65.460342,144.797437,0.31,0.153534,2.211987,"Fully Implicit Null binaire, en ligne"

### Fully Implicit Recommender avec nuls et indicateur binaire, en ligne version batch

In [44]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 8.91 s, sys: 73.8 ms, total: 8.99 s
Wall time: 14.3 s

In [45]:
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df, 'Fully Implicit Null binaire, en ligne (batch)')
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,995.330762,76.424984,224.705326,0.33,0.225759,2.940208,"Fully Implicit Null binaire, en ligne (batch)"
1,995.722167,77.256141,152.189966,0.26,0.152844,1.969940,"Fully Implicit Null binaire, en ligne (batch)"
2,999.400836,76.217189,161.746117,0.27,0.161843,2.122174,"Fully Implicit Null binaire, en ligne (batch)"
3,905.852380,77.837074,231.519452,0.34,0.255582,2.974411,"Fully Implicit Null binaire, en ligne (batch)"
4,989.092200,67.814648,152.699246,0.32,0.154383,2.251715,"Fully Implicit Null binaire, en ligne (batch)"

### Fully Implicit Recommender avec nuls et indicateur special, hors ligne

In [46]:
%%time
FullyImplicitRecommenderWithNull_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.29 s, sys: 109 ms, total: 9.4 s
Wall time: 23.9 s

In [47]:
FullyImplicitRecommenderWithNull_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_df, 'Fully Implicit Null special, hors ligne')
FullyImplicitRecommenderWithNull_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,868.953895,59.960186,153.301424,0.28,0.176421,2.556720,"Fully Implicit Null special, hors ligne"
1,957.781485,67.106916,192.059080,0.30,0.200525,2.861986,"Fully Implicit Null special, hors ligne"
2,954.553109,65.225953,148.956574,0.28,0.156048,2.283701,"Fully Implicit Null special, hors ligne"
3,962.765536,71.775968,133.120296,0.28,0.138269,1.854664,"Fully Implicit Null special, hors ligne"
4,986.921712,61.927945,101.403314,0.28,0.102747,1.637440,"Fully Implicit Null special, hors ligne"

### Fully Implicit Recommender avec nuls et indicateur special, en ligne

In [48]:
%%time
FullyImplicitRecommenderWithNull_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.67 s, sys: 105 ms, total: 9.77 s
Wall time: 18.6 s

In [49]:
FullyImplicitRecommenderWithNull_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_online_df, 'Fully Implicit Null special, en ligne')
FullyImplicitRecommenderWithNull_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,980.294741,51.523393,131.546144,0.34,0.134190,2.553134,"Fully Implicit Null special, en ligne"
1,991.675214,76.549436,175.374178,0.30,0.176846,2.290992,"Fully Implicit Null special, en ligne"
2,988.373501,81.053630,237.751299,0.35,0.240548,2.933259,"Fully Implicit Null special, en ligne"
3,988.297312,76.090031,240.377462,0.38,0.243224,3.159119,"Fully Implicit Null special, en ligne"
4,927.988897,69.750082,169.540002,0.31,0.182696,2.430678,"Fully Implicit Null special, en ligne"

### Fully Implicit Recommender avec nuls et indicateur special, en ligne version batch

In [50]:
%%time
FullyImplicitRecommenderWithNull_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.3 s, sys: 90.5 ms, total: 9.39 s
Wall time: 16.9 s

In [51]:
FullyImplicitRecommenderWithNull_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_online_batch_df, 'Fully Implicit Null special, en ligne (batch)')
FullyImplicitRecommenderWithNull_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,987.335073,85.317336,167.806925,0.25,0.169959,1.966856,"Fully Implicit Null special, en ligne (batch)"
1,952.452597,69.238879,152.632454,0.27,0.160252,2.204433,"Fully Implicit Null special, en ligne (batch)"
2,954.084010,64.718268,172.404736,0.31,0.180702,2.663927,"Fully Implicit Null special, en ligne (batch)"
3,968.801925,75.396519,144.213320,0.22,0.148857,1.912732,"Fully Implicit Null special, en ligne (batch)"
4,930.600017,68.990005,140.539988,0.35,0.151021,2.037107,"Fully Implicit Null special, en ligne (batch)"

## Aggregation des rÃ©sutats

In [52]:
all_results = pd.concat( (
    ImplicitRecommenderSimple_df_normalized,
    ImplicitRecommenderSimple_online_df_normalized,
    ImplicitRecommenderSimple_online_batch_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_online_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_online_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized,
    ImplicitRecommenderWithNull_df_normalized,
    ImplicitRecommenderWithNull_online_df_normalized,
    ImplicitRecommenderWithNull_online_batch_df_normalized,
    
    FullyImplicitRecommenderSimple_df_normalized,
    FullyImplicitRecommenderSimple_online_df_normalized,
    FullyImplicitRecommenderSimple_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_df_normalized,
    FullyImplicitRecommenderWithNull_online_df_normalized,
    FullyImplicitRecommenderWithNull_online_batch_df_normalized
), axis = 0)

In [53]:
aggregat = all_results.groupby('recommendation').mean()

### Classement ratio de recommandations effectives

In [54]:
col = 'good_reco_ratio' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### Classement par average reward normalisÃ©e (max)

In [55]:
col = 'average_reward_normalized_max' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### Classement par average reward normalisÃ©e (mean)

In [56]:
col = 'average_reward_normalized_mean' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### RÃ©sumÃ© (classÃ© par average_reward)

In [57]:
cm = sns.light_palette("green", as_cmap=True)
col = 'average_reward' 
aggregat.sort_values(col, ascending=False)\
    .style.background_gradient(cmap=cm).highlight_max(color='red')

La recommendation prenant en charge les nulls semble meilleure. <br>
  1) Null binaire, hors ligne<br>
  2) Fully Implicit Null special, en ligne<br>
  3) Null binaire, en ligne <br>

Precedemmant:
La recommendation prenant en charge les nulls semble meilleure. <br>
  1) Null secial en ligne (batch) <br>
  2) Fully Implicit Null special, en ligne (batch) <br>
  3) Null, hors ligne <br>