# Recommandation avec cold start

In [5]:
import pandas as pd

import seaborn as sns

from deep_implicit_feedback_recsys import *

from cold_star_recommender import *

from recommender_evaluation import *

In [6]:
def normalized_results(df, recommender_type):
    df['average_reward_normalized_max'] = df['average_reward'] / df['max_price']
    df['average_reward_normalized_mean'] = df['average_reward'] / df['mean_price']
    df['recommendation'] = recommender_type
    return df

In [7]:
n_loop = 10
n_pred = 100
online_batch_size = n_pred // 10

user_dim = item_dim = 8
n_hidden = 1
hidden_size = 64
dropout = 0.1
l2_reg = 0

## Mesures d'Ã©chantillon

### Implicit Recommender Simple, hors ligne

In [8]:
%%time
ImplicitRecommenderSimple_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                      ImplicitRecommenderClass=ImplicitRecommenderSimple, 
                                                                      n_loop=n_loop, n_pred=n_pred,
                                                                      user_dim=user_dim, item_dim=item_dim,
                                                                      n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                      dropout=dropout, l2_reg=l2_reg)

CPU times: user 28.4 s, sys: 442 ms, total: 28.9 s
Wall time: 40.5 s

In [9]:
ImplicitRecommenderSimple_df_normalized = normalized_results(ImplicitRecommenderSimple_df, 'Simple, hors ligne')
ImplicitRecommenderSimple_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,959.737052,73.746539,61.596141,0.32,0.064180,0.835241,"Simple, hors ligne"
1,996.846187,70.448032,105.031519,0.35,0.105364,1.490908,"Simple, hors ligne"
2,983.485803,78.028259,135.889914,0.33,0.138172,1.741547,"Simple, hors ligne"
3,980.204459,68.611955,78.895781,0.28,0.080489,1.149884,"Simple, hors ligne"
4,987.541172,67.009611,95.596585,0.36,0.096803,1.426610,"Simple, hors ligne"
5,939.570760,82.625846,97.368155,0.33,0.103630,1.178422,"Simple, hors ligne"
6,983.476780,68.696256,85.038388,0.27,0.086467,1.237890,"Simple, hors ligne"
7,979.671907,63.944929,127.366202,0.38,0.130009,1.991811,"Simple, hors ligne"
8,992.369747,77.885127,120.222295,0.46,0.121147,1.543585,"Simple, hors ligne"
9,982.953384,86.216667,48.279875,0.25,0.049117,0.559983,"Simple, hors ligne"

### Implicit Recommender Simple, en ligne

In [10]:
%%time
ImplicitRecommenderSimple_online_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=1,
                                                                             user_dim=user_dim, item_dim=item_dim,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 34.1 s, sys: 494 ms, total: 34.6 s
Wall time: 54.5 s

In [11]:
ImplicitRecommenderSimple_online_df_normalized = normalized_results(ImplicitRecommenderSimple_online_df, 'Simple, en ligne')
ImplicitRecommenderSimple_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,972.848692,68.776290,99.423666,0.30,0.102198,1.445610,"Simple, en ligne"
1,945.077172,55.303744,261.602161,0.40,0.276805,4.730279,"Simple, en ligne"
2,916.910786,65.853997,242.704934,0.31,0.264699,3.685500,"Simple, en ligne"
3,992.426178,80.158920,254.363224,0.33,0.256304,3.173237,"Simple, en ligne"
4,977.096174,78.014046,78.038736,0.18,0.079868,1.000316,"Simple, en ligne"
5,996.571870,72.684800,120.971361,0.37,0.121387,1.664328,"Simple, en ligne"
6,886.562526,72.167547,236.517135,0.31,0.266780,3.277334,"Simple, en ligne"
7,944.297361,57.890893,86.293806,0.44,0.091384,1.490628,"Simple, en ligne"
8,923.621669,65.775868,254.236294,0.37,0.275260,3.865191,"Simple, en ligne"
9,943.022143,58.965789,161.165768,0.22,0.170903,2.733208,"Simple, en ligne"

### Implicit Recommender Simple, en ligne version batch

In [12]:
%%time
ImplicitRecommenderSimple_online_batch_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             user_dim=user_dim, item_dim=item_dim,
                                                                             online_batch_size=online_batch_size,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 39.5 s, sys: 521 ms, total: 40 s
Wall time: 54.3 s

In [13]:
ImplicitRecommenderSimple_online_batch_df_normalized = normalized_results(ImplicitRecommenderSimple_online_batch_df, 'Simple, en ligne (batch)')
ImplicitRecommenderSimple_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,993.930552,61.756401,92.358685,0.33,0.092923,1.495532,"Simple, en ligne (batch)"
1,937.388470,66.014776,91.330081,0.28,0.097430,1.383479,"Simple, en ligne (batch)"
2,941.895181,74.351325,82.921620,0.32,0.088037,1.115268,"Simple, en ligne (batch)"
3,978.412197,80.648464,103.851215,0.39,0.106143,1.287702,"Simple, en ligne (batch)"
4,977.236264,71.345237,229.321811,0.28,0.234664,3.214255,"Simple, en ligne (batch)"
5,969.230251,55.214068,199.310121,0.26,0.205638,3.609771,"Simple, en ligne (batch)"
6,988.780844,83.837401,86.132071,0.33,0.087109,1.027370,"Simple, en ligne (batch)"
7,961.347955,58.628357,107.214414,0.34,0.111525,1.828713,"Simple, en ligne (batch)"
8,958.688261,74.172479,361.656084,0.44,0.377241,4.875880,"Simple, en ligne (batch)"
9,988.017145,92.644722,197.550487,0.25,0.199946,2.132345,"Simple, en ligne (batch)"

### Implicit Recommender avec nuls sans indicateur, hors ligne

In [14]:
%%time
ImplicitRecommenderWithNull_no_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator, 
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 47.4 s, sys: 660 ms, total: 48.1 s
Wall time: 56.9 s

In [15]:
ImplicitRecommenderWithNull_no_indicator_df_normalized = normalized_results(ImplicitRecommenderWithNull_no_indicator_df, 'Null, hors ligne')
ImplicitRecommenderWithNull_no_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,906.892092,76.118942,85.102518,0.30,0.093840,1.118020,"Null, hors ligne"
1,995.424876,66.010686,139.754115,0.30,0.140396,2.117144,"Null, hors ligne"
2,972.839505,71.598976,264.218849,0.32,0.271596,3.690260,"Null, hors ligne"
3,957.594350,73.054839,248.845306,0.32,0.259865,3.406281,"Null, hors ligne"
4,943.452975,63.266867,181.887980,0.26,0.192790,2.874933,"Null, hors ligne"
5,965.598134,67.901070,317.636490,0.36,0.328953,4.677931,"Null, hors ligne"
6,990.806311,68.589820,224.031767,0.28,0.226111,3.266254,"Null, hors ligne"
7,995.363368,59.269212,287.001618,0.40,0.288339,4.842339,"Null, hors ligne"
8,993.323094,70.840044,106.775370,0.30,0.107493,1.507274,"Null, hors ligne"
9,976.742046,60.449901,58.608571,0.31,0.060004,0.969540,"Null, hors ligne"

### Implicit Recommender avec nuls sans indicateur, en ligne

In [16]:
%%time
ImplicitRecommenderWithNull_no_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 53.5 s, sys: 692 ms, total: 54.2 s
Wall time: 1min 3s

In [17]:
ImplicitRecommenderWithNull_no_indicator_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_no_indicator_online_df,
                                                                                   'Null, en ligne')
ImplicitRecommenderWithNull_no_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,952.262807,75.734863,247.314599,0.33,0.259713,3.265532,"Null, en ligne"
1,917.676865,57.296364,145.950877,0.41,0.159044,2.547297,"Null, en ligne"
2,912.079811,64.798087,110.201170,0.24,0.120824,1.700686,"Null, en ligne"
3,963.113279,61.451105,180.049601,0.26,0.186945,2.929965,"Null, en ligne"
4,992.480323,78.690023,112.429248,0.31,0.113281,1.428761,"Null, en ligne"
5,984.356955,73.534389,183.582122,0.31,0.186500,2.496548,"Null, en ligne"
6,966.007373,83.860387,377.387794,0.46,0.390668,4.500191,"Null, en ligne"
7,977.222426,65.867878,228.079800,0.32,0.233396,3.462686,"Null, en ligne"
8,908.430041,69.939080,119.407841,0.41,0.131444,1.707312,"Null, en ligne"
9,949.650683,68.143028,251.034169,0.33,0.264344,3.683930,"Null, en ligne"

### Implicit Recommender avec nuls sans indicateur, en ligne version batch

In [18]:
%%time
ImplicitRecommenderWithNull_no_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 58.4 s, sys: 646 ms, total: 59 s
Wall time: 1min 10s

In [19]:
ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_no_indicator_online_batch_df, 'Null, en ligne (batch)')
ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,981.357591,87.640337,305.540323,0.36,0.311345,3.486298,"Null, en ligne (batch)"
1,960.815118,79.524320,92.389501,0.40,0.096157,1.161777,"Null, en ligne (batch)"
2,957.337154,71.722082,117.689832,0.28,0.122935,1.640915,"Null, en ligne (batch)"
3,986.358766,79.385204,68.263953,0.16,0.069208,0.859908,"Null, en ligne (batch)"
4,999.301681,81.165717,350.821003,0.39,0.351066,4.322281,"Null, en ligne (batch)"
5,981.941627,77.425946,179.532639,0.36,0.182834,2.318766,"Null, en ligne (batch)"
6,980.042878,71.451976,217.988383,0.28,0.222427,3.050838,"Null, en ligne (batch)"
7,988.382647,59.614288,302.099730,0.36,0.305651,5.067573,"Null, en ligne (batch)"
8,995.933466,70.070590,82.715065,0.28,0.083053,1.180453,"Null, en ligne (batch)"
9,949.838215,73.237920,234.462037,0.30,0.246844,3.201375,"Null, en ligne (batch)"

### Implicit Recommender avec nuls et indicateur binaire, hors ligne

In [20]:
%%time
ImplicitRecommenderWithNull_binary_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 1min 6s, sys: 713 ms, total: 1min 7s
Wall time: 1min 29s

In [21]:
ImplicitRecommenderWithNull_binary_indicator_df_normalized = normalized_results(ImplicitRecommenderWithNull_binary_indicator_df,
                                                                                'Null binaire, hors ligne')
ImplicitRecommenderWithNull_binary_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,939.906570,73.409844,163.117234,0.25,0.173546,2.222008,"Null binaire, hors ligne"
1,999.239368,71.089474,64.924730,0.29,0.064974,0.913282,"Null binaire, hors ligne"
2,990.837456,74.169952,237.340162,0.29,0.239535,3.199950,"Null binaire, hors ligne"
3,768.012163,57.250785,195.942673,0.32,0.255130,3.422533,"Null binaire, hors ligne"
4,972.565481,71.185162,163.081615,0.22,0.167682,2.290950,"Null binaire, hors ligne"
5,994.221225,63.359850,137.429396,0.27,0.138228,2.169030,"Null binaire, hors ligne"
6,991.977432,74.055141,218.343486,0.29,0.220109,2.948391,"Null binaire, hors ligne"
7,966.976131,79.208207,324.816864,0.39,0.335910,4.100798,"Null binaire, hors ligne"
8,997.704038,67.118541,71.092050,0.27,0.071256,1.059201,"Null binaire, hors ligne"
9,967.495449,58.026806,293.624900,0.36,0.303490,5.060160,"Null binaire, hors ligne"

### Implicit Recommender avec nuls et indicateur binaire, en ligne

In [22]:
%%time
ImplicitRecommenderWithNull_binary_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 1min 13s, sys: 683 ms, total: 1min 14s
Wall time: 1min 27s

In [23]:
ImplicitRecommenderWithNull_binary_indicator_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_binary_indicator_online_df,
                                                                                       'Null binaire, en ligne')
ImplicitRecommenderWithNull_binary_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,980.739344,68.167225,166.352436,0.21,0.169619,2.440358,"Null binaire, en ligne"
1,969.504367,70.696348,106.181101,0.32,0.109521,1.501932,"Null binaire, en ligne"
2,942.753825,63.313826,141.611772,0.19,0.150211,2.236664,"Null binaire, en ligne"
3,973.511031,66.820756,236.624704,0.35,0.243063,3.541186,"Null binaire, en ligne"
4,986.943080,66.936005,180.051306,0.24,0.182433,2.689902,"Null binaire, en ligne"
5,985.078820,71.881665,122.340871,0.31,0.124194,1.701976,"Null binaire, en ligne"
6,910.777045,58.079563,57.196600,0.28,0.062800,0.984797,"Null binaire, en ligne"
7,984.595523,76.420472,113.245538,0.32,0.115017,1.481874,"Null binaire, en ligne"
8,999.349833,68.560430,92.576408,0.33,0.092637,1.350289,"Null binaire, en ligne"
9,984.897986,82.463890,177.503050,0.22,0.180225,2.152494,"Null binaire, en ligne"

### Implicit Recommender avec nuls et indicateur binaire, en ligne version batch

In [24]:
%%time
ImplicitRecommenderWithNull_binary_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 1min 19s, sys: 732 ms, total: 1min 20s
Wall time: 1min 32s

In [25]:
ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_binary_indicator_online_batch_df, 'Null binaire, en ligne (batch)')
ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,961.384506,62.627427,304.913373,0.38,0.317161,4.868688,"Null binaire, en ligne (batch)"
1,998.329365,68.955438,88.367424,0.20,0.088515,1.281515,"Null binaire, en ligne (batch)"
2,957.754750,72.368257,227.443665,0.27,0.237476,3.142865,"Null binaire, en ligne (batch)"
3,966.074473,64.299806,37.978444,0.26,0.039312,0.590646,"Null binaire, en ligne (batch)"
4,967.488928,83.538120,131.933818,0.39,0.136367,1.579325,"Null binaire, en ligne (batch)"
5,970.164401,65.478797,265.229811,0.34,0.273386,4.050621,"Null binaire, en ligne (batch)"
6,912.667360,74.477402,108.459916,0.40,0.118838,1.456280,"Null binaire, en ligne (batch)"
7,996.601054,69.341370,95.789780,0.33,0.096116,1.381423,"Null binaire, en ligne (batch)"
8,929.212136,80.119879,111.329969,0.30,0.119811,1.389542,"Null binaire, en ligne (batch)"
9,992.712030,72.235114,117.042734,0.36,0.117902,1.620302,"Null binaire, en ligne (batch)"

### Implicit Recommender avec nuls et indicateur special, hors ligne

In [26]:
%%time
ImplicitRecommenderWithNull_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 1min 24s, sys: 760 ms, total: 1min 24s
Wall time: 1min 33s

In [27]:
ImplicitRecommenderWithNull_df_normalized = normalized_results(ImplicitRecommenderWithNull_df, 'Null special, hors ligne')
ImplicitRecommenderWithNull_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,976.266959,53.932201,181.535563,0.23,0.185949,3.365996,"Null special, hors ligne"
1,969.046749,80.590884,274.504182,0.32,0.283272,3.406144,"Null special, hors ligne"
2,992.213472,76.427036,172.700829,0.30,0.174056,2.259682,"Null special, hors ligne"
3,994.241556,94.761007,308.282773,0.37,0.310068,3.253266,"Null special, hors ligne"
4,977.306626,69.921156,207.293672,0.25,0.212107,2.964677,"Null special, hors ligne"
5,962.747701,60.992898,253.800347,0.34,0.263621,4.161146,"Null special, hors ligne"
6,937.623321,72.018828,278.346281,0.39,0.296864,3.864910,"Null special, hors ligne"
7,956.742618,78.855812,230.066161,0.29,0.240468,2.917555,"Null special, hors ligne"
8,993.912691,71.203494,97.460283,0.25,0.098057,1.368757,"Null special, hors ligne"
9,994.174756,78.021929,246.472597,0.33,0.247917,3.159017,"Null special, hors ligne"

### Implicit Recommender avec nuls et indicateur special, en ligne

In [28]:
%%time
ImplicitRecommenderWithNull_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 1min 33s, sys: 803 ms, total: 1min 34s
Wall time: 1min 44s

In [29]:
ImplicitRecommenderWithNull_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_online_df, 'Null special, en ligne')
ImplicitRecommenderWithNull_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,993.535579,78.697664,297.555022,0.34,0.299491,3.780989,"Null special, en ligne"
1,889.343352,71.358040,71.352323,0.30,0.080230,0.999920,"Null special, en ligne"
2,961.442391,68.471930,194.625129,0.27,0.202430,2.842408,"Null special, en ligne"
3,985.731746,78.025155,271.077836,0.34,0.275002,3.474236,"Null special, en ligne"
4,979.809690,76.352991,139.831921,0.23,0.142713,1.831388,"Null special, en ligne"
5,992.795853,72.333716,256.988671,0.31,0.258853,3.552820,"Null special, en ligne"
6,984.251889,75.420819,212.750514,0.29,0.216155,2.820846,"Null special, en ligne"
7,950.388415,75.020805,235.172022,0.31,0.247448,3.134757,"Null special, en ligne"
8,989.661670,73.097547,323.298564,0.39,0.326676,4.422837,"Null special, en ligne"
9,983.709041,71.731863,226.242283,0.30,0.229989,3.154000,"Null special, en ligne"

### Implicit Recommender avec nuls et indicateur special, en ligne version batch

In [30]:
%%time
ImplicitRecommenderWithNull_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 1min 40s, sys: 759 ms, total: 1min 41s
Wall time: 2min 1s

In [31]:
ImplicitRecommenderWithNull_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_online_batch_df, 'Null special, en ligne (batch)')
ImplicitRecommenderWithNull_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,934.198291,69.651051,136.373001,0.24,0.145979,1.957946,"Null special, en ligne (batch)"
1,988.776425,67.774755,151.632779,0.24,0.153354,2.237305,"Null special, en ligne (batch)"
2,995.454266,82.541637,172.817732,0.25,0.173607,2.093704,"Null special, en ligne (batch)"
3,996.112668,64.039142,180.911395,0.27,0.181617,2.825013,"Null special, en ligne (batch)"
4,952.545801,65.239406,257.118256,0.32,0.269927,3.941150,"Null special, en ligne (batch)"
5,986.132007,74.736158,223.596304,0.29,0.226741,2.991809,"Null special, en ligne (batch)"
6,991.562008,61.882849,213.199197,0.28,0.215013,3.445207,"Null special, en ligne (batch)"
7,952.167620,74.535208,282.883858,0.44,0.297095,3.795305,"Null special, en ligne (batch)"
8,991.631506,73.578608,83.406072,0.35,0.084110,1.133564,"Null special, en ligne (batch)"
9,947.767427,83.775058,272.494933,0.35,0.287512,3.252698,"Null special, en ligne (batch)"

### Fully Implicit Recommender Simple, hors ligne

In [32]:
%%time
FullyImplicitRecommenderSimple_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                      ImplicitRecommenderClass=ImplicitRecommenderSimple, 
                                                                      n_loop=n_loop, n_pred=n_pred,
                                                                      user_dim=user_dim, item_dim=item_dim,
                                                                      n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                      dropout=dropout, l2_reg=l2_reg)

CPU times: user 22.6 s, sys: 180 ms, total: 22.8 s
Wall time: 33.4 s

In [33]:
FullyImplicitRecommenderSimple_df_normalized = normalized_results(FullyImplicitRecommenderSimple_df, 'Fully Implicit Simple, hors ligne')
FullyImplicitRecommenderSimple_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,992.651771,80.274909,253.583186,0.40,0.255460,3.158935,"Fully Implicit Simple, hors ligne"
1,992.704254,69.880528,215.497910,0.35,0.217082,3.083805,"Fully Implicit Simple, hors ligne"
2,973.430045,66.188986,214.844512,0.33,0.220709,3.245925,"Fully Implicit Simple, hors ligne"
3,987.815364,71.533747,198.602764,0.39,0.201053,2.776351,"Fully Implicit Simple, hors ligne"
4,821.479482,59.201016,185.257775,0.42,0.225517,3.129301,"Fully Implicit Simple, hors ligne"
5,975.877162,69.606900,121.438036,0.27,0.124440,1.744626,"Fully Implicit Simple, hors ligne"
6,994.213779,69.314248,201.573085,0.29,0.202746,2.908105,"Fully Implicit Simple, hors ligne"
7,973.798054,79.939456,199.869294,0.30,0.205247,2.500258,"Fully Implicit Simple, hors ligne"
8,969.586913,80.233126,150.738899,0.35,0.155467,1.878761,"Fully Implicit Simple, hors ligne"
9,969.624857,80.187657,177.535734,0.32,0.183097,2.214003,"Fully Implicit Simple, hors ligne"

### Fully Implicit Recommender Simple, en ligne

In [34]:
%%time
FullyImplicitRecommenderSimple_online_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=1,
                                                                             user_dim=user_dim, item_dim=item_dim,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 22.9 s, sys: 199 ms, total: 23.1 s
Wall time: 34.3 s

In [35]:
FullyImplicitRecommenderSimple_online_df_normalized = normalized_results(FullyImplicitRecommenderSimple_online_df, 'Fully Implicit Simple, en ligne')
FullyImplicitRecommenderSimple_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,989.773969,70.752858,215.740050,0.42,0.217969,3.049206,"Fully Implicit Simple, en ligne"
1,987.380928,68.129398,169.348114,0.28,0.171512,2.485683,"Fully Implicit Simple, en ligne"
2,990.233741,73.977356,208.721105,0.33,0.210780,2.821419,"Fully Implicit Simple, en ligne"
3,965.849636,65.031678,145.973292,0.29,0.151135,2.244649,"Fully Implicit Simple, en ligne"
4,978.466504,75.327849,166.006351,0.28,0.169660,2.203785,"Fully Implicit Simple, en ligne"
5,958.723540,67.539273,118.021506,0.29,0.123103,1.747450,"Fully Implicit Simple, en ligne"
6,969.567952,81.555003,226.395871,0.35,0.233502,2.775990,"Fully Implicit Simple, en ligne"
7,999.704752,86.088826,138.789250,0.24,0.138830,1.612163,"Fully Implicit Simple, en ligne"
8,988.086156,70.859867,174.856407,0.29,0.176965,2.467637,"Fully Implicit Simple, en ligne"
9,997.469469,75.692548,240.474211,0.41,0.241084,3.176987,"Fully Implicit Simple, en ligne"

### Fully Implicit Recommender Simple, en ligne version batch

In [36]:
%%time
FullyImplicitRecommenderSimple_online_batch_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=online_batch_size,
                                                                             user_dim=user_dim, item_dim=item_dim,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.8 s, sys: 199 ms, total: 22 s
Wall time: 38.8 s

In [37]:
FullyImplicitRecommenderSimple_online_batch_df_normalized = normalized_results(FullyImplicitRecommenderSimple_online_batch_df, 'Fully Implicit Simple, en ligne (batch)')
FullyImplicitRecommenderSimple_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,997.942636,68.588068,191.256489,0.36,0.191651,2.788480,"Fully Implicit Simple, en ligne (batch)"
1,966.290327,77.082980,222.617568,0.41,0.230384,2.888025,"Fully Implicit Simple, en ligne (batch)"
2,953.336856,69.085402,189.136151,0.35,0.198394,2.737715,"Fully Implicit Simple, en ligne (batch)"
3,979.712880,69.649358,161.716412,0.27,0.165065,2.321865,"Fully Implicit Simple, en ligne (batch)"
4,956.877129,68.594667,201.477658,0.30,0.210558,2.937220,"Fully Implicit Simple, en ligne (batch)"
5,988.795922,80.949563,203.368567,0.27,0.205673,2.512287,"Fully Implicit Simple, en ligne (batch)"
6,989.680674,69.614588,207.233203,0.42,0.209394,2.976865,"Fully Implicit Simple, en ligne (batch)"
7,992.109051,66.890780,153.896882,0.32,0.155121,2.300719,"Fully Implicit Simple, en ligne (batch)"
8,979.032168,74.229058,113.232680,0.17,0.115658,1.525450,"Fully Implicit Simple, en ligne (batch)"
9,967.686683,73.919845,153.816484,0.30,0.158953,2.080855,"Fully Implicit Simple, en ligne (batch)"

### Fully Implicit Recommender avec nuls sans indicateur, hors ligne

In [38]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator, 
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.9 s, sys: 209 ms, total: 22.1 s
Wall time: 34.3 s

In [39]:
FullyImplicitRecommenderWithNull_no_indicator_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_no_indicator_df, 'Fully Implicit Null, hors ligne')
FullyImplicitRecommenderWithNull_no_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,969.331923,74.189542,167.708529,0.32,0.173015,2.260541,"Fully Implicit Null, hors ligne"
1,985.947796,63.885437,125.247149,0.26,0.127032,1.960496,"Fully Implicit Null, hors ligne"
2,890.268926,64.224578,156.306327,0.34,0.175572,2.433746,"Fully Implicit Null, hors ligne"
3,927.526435,73.197475,192.010207,0.36,0.207013,2.623181,"Fully Implicit Null, hors ligne"
4,985.045392,77.830823,187.616568,0.29,0.190465,2.410569,"Fully Implicit Null, hors ligne"
5,964.517854,70.859016,126.765040,0.22,0.131428,1.788975,"Fully Implicit Null, hors ligne"
6,987.388856,80.918198,137.391353,0.26,0.139146,1.697904,"Fully Implicit Null, hors ligne"
7,993.475774,81.395931,137.267966,0.30,0.138169,1.686423,"Fully Implicit Null, hors ligne"
8,985.166218,84.999731,172.035320,0.25,0.174626,2.023951,"Fully Implicit Null, hors ligne"
9,962.649625,76.463913,246.195761,0.35,0.255748,3.219764,"Fully Implicit Null, hors ligne"

### Fully Implicit Recommender avec nuls sans indicateur, en ligne

In [40]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.6 s, sys: 158 ms, total: 21.8 s
Wall time: 32.3 s

In [41]:
FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_no_indicator_online_df,
                                                                                   'Fully Implicit Null, en ligne')
FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,938.338863,76.122699,156.590745,0.32,0.166881,2.057083,"Fully Implicit Null, en ligne"
1,961.585969,69.541308,252.222427,0.39,0.262298,3.626944,"Fully Implicit Null, en ligne"
2,982.805260,75.312749,203.984480,0.29,0.207553,2.708499,"Fully Implicit Null, en ligne"
3,910.646538,75.542047,164.989913,0.31,0.181179,2.184081,"Fully Implicit Null, en ligne"
4,978.294493,73.337514,135.906221,0.24,0.138922,1.853161,"Fully Implicit Null, en ligne"
5,978.527447,78.282657,189.403401,0.34,0.193560,2.419481,"Fully Implicit Null, en ligne"
6,996.024466,76.202433,148.295882,0.27,0.148888,1.946078,"Fully Implicit Null, en ligne"
7,957.749155,60.336954,166.995909,0.38,0.174363,2.767722,"Fully Implicit Null, en ligne"
8,989.303831,66.814617,139.845076,0.30,0.141357,2.093031,"Fully Implicit Null, en ligne"
9,913.349470,71.839493,140.694763,0.26,0.154043,1.958460,"Fully Implicit Null, en ligne"

### Fully Implicit Recommender avec nuls sans indicateur, en ligne version batch

In [42]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.8 s, sys: 201 ms, total: 22 s
Wall time: 32.2 s

In [43]:
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_no_indicator_online_batch_df, 'Fully Implicit Null, en ligne (batch)')
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,902.742085,72.310872,213.439501,0.35,0.236435,2.951693,"Fully Implicit Null, en ligne (batch)"
1,995.807997,82.688206,233.354047,0.31,0.234336,2.822096,"Fully Implicit Null, en ligne (batch)"
2,993.714307,73.188397,202.817784,0.33,0.204101,2.771174,"Fully Implicit Null, en ligne (batch)"
3,984.444422,75.290803,94.718755,0.21,0.096215,1.258039,"Fully Implicit Null, en ligne (batch)"
4,994.328566,62.319306,187.878114,0.38,0.188950,3.014766,"Fully Implicit Null, en ligne (batch)"
5,916.648635,75.430824,212.608535,0.39,0.231941,2.818590,"Fully Implicit Null, en ligne (batch)"
6,973.577473,84.479791,236.863704,0.32,0.243292,2.803791,"Fully Implicit Null, en ligne (batch)"
7,991.445892,64.914036,103.857855,0.25,0.104754,1.599929,"Fully Implicit Null, en ligne (batch)"
8,992.104195,70.169982,179.180244,0.33,0.180606,2.553517,"Fully Implicit Null, en ligne (batch)"
9,985.933750,67.238583,190.216544,0.45,0.192930,2.828979,"Fully Implicit Null, en ligne (batch)"

### Fully Implicit Recommender avec nuls et indicateur binaire, hors ligne

In [44]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.9 s, sys: 147 ms, total: 22.1 s
Wall time: 32.2 s

In [45]:
FullyImplicitRecommenderWithNull_binary_indicator_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_df,
                                                                                'Fully Implicit Null binaire, hors ligne')
FullyImplicitRecommenderWithNull_binary_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,942.243330,76.102243,133.785147,0.25,0.141986,1.757966,"Fully Implicit Null binaire, hors ligne"
1,965.838659,64.140582,132.511910,0.26,0.137199,2.065961,"Fully Implicit Null binaire, hors ligne"
2,987.243338,78.866723,167.264242,0.29,0.169426,2.120847,"Fully Implicit Null binaire, hors ligne"
3,982.664980,73.028761,178.914318,0.30,0.182071,2.449916,"Fully Implicit Null binaire, hors ligne"
4,984.364318,75.143304,188.194223,0.35,0.191184,2.504471,"Fully Implicit Null binaire, hors ligne"
5,982.601981,66.816772,230.690829,0.40,0.234775,3.452589,"Fully Implicit Null binaire, hors ligne"
6,989.563807,69.863206,153.394251,0.30,0.155012,2.195637,"Fully Implicit Null binaire, hors ligne"
7,989.710575,68.005513,138.558095,0.32,0.139999,2.037454,"Fully Implicit Null binaire, hors ligne"
8,983.117456,75.605808,249.478231,0.38,0.253762,3.299723,"Fully Implicit Null binaire, hors ligne"
9,967.558039,73.049247,196.201603,0.30,0.202780,2.685881,"Fully Implicit Null binaire, hors ligne"

### Fully Implicit Recommender avec nuls et indicateur binaire, en ligne

In [46]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 22.3 s, sys: 175 ms, total: 22.5 s
Wall time: 33.5 s

In [47]:
FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_online_df,
                                                                                       'Fully Implicit Null binaire, en ligne')
FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,983.843291,66.271063,155.377254,0.29,0.157929,2.344572,"Fully Implicit Null binaire, en ligne"
1,923.380636,74.789420,186.914580,0.39,0.202424,2.499212,"Fully Implicit Null binaire, en ligne"
2,949.255560,81.725358,230.612092,0.30,0.242940,2.821794,"Fully Implicit Null binaire, en ligne"
3,998.427543,75.457659,248.172828,0.42,0.248564,3.288902,"Fully Implicit Null binaire, en ligne"
4,983.341448,60.262429,117.871745,0.28,0.119869,1.955974,"Fully Implicit Null binaire, en ligne"
5,993.232717,70.402084,169.262297,0.30,0.170416,2.404223,"Fully Implicit Null binaire, en ligne"
6,974.808225,71.047534,137.626671,0.29,0.141183,1.937107,"Fully Implicit Null binaire, en ligne"
7,949.879988,67.317482,117.076453,0.30,0.123254,1.739169,"Fully Implicit Null binaire, en ligne"
8,983.685404,66.673681,199.444894,0.28,0.202753,2.991359,"Fully Implicit Null binaire, en ligne"
9,982.228871,78.119004,200.096720,0.30,0.203717,2.561435,"Fully Implicit Null binaire, en ligne"

### Fully Implicit Recommender avec nuls et indicateur binaire, en ligne version batch

In [48]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 22.8 s, sys: 180 ms, total: 23 s
Wall time: 35.2 s

In [49]:
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df, 'Fully Implicit Null binaire, en ligne (batch)')
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,918.492456,52.805143,180.969552,0.40,0.197029,3.427120,"Fully Implicit Null binaire, en ligne (batch)"
1,975.593134,75.045986,184.779185,0.30,0.189402,2.462213,"Fully Implicit Null binaire, en ligne (batch)"
2,988.973669,69.682103,230.036074,0.33,0.232601,3.301222,"Fully Implicit Null binaire, en ligne (batch)"
3,976.853721,74.476388,172.874233,0.33,0.176970,2.321195,"Fully Implicit Null binaire, en ligne (batch)"
4,968.759370,86.775230,233.356926,0.30,0.240882,2.689211,"Fully Implicit Null binaire, en ligne (batch)"
5,993.110567,76.929469,166.394331,0.27,0.167549,2.162947,"Fully Implicit Null binaire, en ligne (batch)"
6,992.416100,78.101643,239.212715,0.34,0.241041,3.062838,"Fully Implicit Null binaire, en ligne (batch)"
7,971.823259,81.238052,240.383941,0.32,0.247354,2.959007,"Fully Implicit Null binaire, en ligne (batch)"
8,936.443096,71.036504,130.027844,0.30,0.138853,1.830437,"Fully Implicit Null binaire, en ligne (batch)"
9,999.457700,70.942922,208.738361,0.32,0.208852,2.942342,"Fully Implicit Null binaire, en ligne (batch)"

### Fully Implicit Recommender avec nuls et indicateur special, hors ligne

In [50]:
%%time
FullyImplicitRecommenderWithNull_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 23.1 s, sys: 207 ms, total: 23.3 s
Wall time: 38.4 s

In [51]:
FullyImplicitRecommenderWithNull_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_df, 'Fully Implicit Null special, hors ligne')
FullyImplicitRecommenderWithNull_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,990.042147,65.724632,132.912646,0.36,0.134249,2.022265,"Fully Implicit Null special, hors ligne"
1,998.440319,79.648861,162.617886,0.30,0.162872,2.041685,"Fully Implicit Null special, hors ligne"
2,985.499274,71.314151,125.615983,0.28,0.127464,1.761445,"Fully Implicit Null special, hors ligne"
3,954.320471,60.647881,107.654463,0.28,0.112807,1.775074,"Fully Implicit Null special, hors ligne"
4,997.258116,72.042600,189.940337,0.40,0.190463,2.636500,"Fully Implicit Null special, hors ligne"
5,986.435821,77.132882,213.603055,0.29,0.216540,2.769287,"Fully Implicit Null special, hors ligne"
6,987.640873,63.259334,151.447456,0.38,0.153343,2.394073,"Fully Implicit Null special, hors ligne"
7,840.054675,53.084713,117.841293,0.28,0.140278,2.219872,"Fully Implicit Null special, hors ligne"
8,990.192061,69.598915,187.491798,0.34,0.189349,2.693890,"Fully Implicit Null special, hors ligne"
9,995.639330,76.843181,218.788158,0.36,0.219746,2.847203,"Fully Implicit Null special, hors ligne"

### Fully Implicit Recommender avec nuls et indicateur special, en ligne

In [52]:
%%time
FullyImplicitRecommenderWithNull_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 23.5 s, sys: 190 ms, total: 23.6 s
Wall time: 49.2 s

In [53]:
FullyImplicitRecommenderWithNull_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_online_df, 'Fully Implicit Null special, en ligne')
FullyImplicitRecommenderWithNull_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,921.926390,70.288489,194.888807,0.38,0.211393,2.772699,"Fully Implicit Null special, en ligne"
1,965.138349,72.999402,157.041146,0.32,0.162714,2.151266,"Fully Implicit Null special, en ligne"
2,986.115738,77.096698,104.551409,0.28,0.106023,1.356107,"Fully Implicit Null special, en ligne"
3,998.243491,78.605075,184.181030,0.34,0.184505,2.343119,"Fully Implicit Null special, en ligne"
4,959.638874,74.616035,200.772971,0.35,0.209217,2.690748,"Fully Implicit Null special, en ligne"
5,993.952225,63.876174,142.100663,0.27,0.142965,2.224627,"Fully Implicit Null special, en ligne"
6,976.071295,76.314993,182.753466,0.30,0.187234,2.394726,"Fully Implicit Null special, en ligne"
7,936.691365,73.039079,197.230085,0.26,0.210560,2.700336,"Fully Implicit Null special, en ligne"
8,987.934193,66.480624,117.763527,0.27,0.119202,1.771396,"Fully Implicit Null special, en ligne"
9,820.801536,72.294852,118.857967,0.29,0.144807,1.644072,"Fully Implicit Null special, en ligne"

### Fully Implicit Recommender avec nuls et indicateur special, en ligne version batch

In [54]:
%%time
FullyImplicitRecommenderWithNull_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           user_dim=user_dim, item_dim=item_dim,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 23.4 s, sys: 182 ms, total: 23.6 s
Wall time: 48.3 s

In [55]:
FullyImplicitRecommenderWithNull_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_online_batch_df, 'Fully Implicit Null special, en ligne (batch)')
FullyImplicitRecommenderWithNull_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,926.072070,71.867006,219.289561,0.37,0.236795,3.051325,"Fully Implicit Null special, en ligne (batch)"
1,963.006486,61.796188,193.100223,0.31,0.200518,3.124792,"Fully Implicit Null special, en ligne (batch)"
2,995.564832,74.114114,200.606469,0.34,0.201500,2.706724,"Fully Implicit Null special, en ligne (batch)"
3,985.733381,81.029192,200.943677,0.33,0.203852,2.479892,"Fully Implicit Null special, en ligne (batch)"
4,967.993626,61.153807,117.678106,0.25,0.121569,1.924297,"Fully Implicit Null special, en ligne (batch)"
5,983.651659,78.050242,224.040164,0.35,0.227764,2.870461,"Fully Implicit Null special, en ligne (batch)"
6,970.810402,70.528831,141.323845,0.30,0.145573,2.003774,"Fully Implicit Null special, en ligne (batch)"
7,952.348217,78.684022,221.160553,0.35,0.232227,2.810743,"Fully Implicit Null special, en ligne (batch)"
8,990.373906,78.639512,189.630616,0.34,0.191474,2.411391,"Fully Implicit Null special, en ligne (batch)"
9,985.319040,78.593223,151.427677,0.25,0.153684,1.926727,"Fully Implicit Null special, en ligne (batch)"

## Aggregation des rÃ©sutats

In [56]:
all_results = pd.concat( (
    ImplicitRecommenderSimple_df_normalized,
    ImplicitRecommenderSimple_online_df_normalized,
    ImplicitRecommenderSimple_online_batch_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_online_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_online_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized,
    ImplicitRecommenderWithNull_df_normalized,
    ImplicitRecommenderWithNull_online_df_normalized,
    ImplicitRecommenderWithNull_online_batch_df_normalized,
    
    FullyImplicitRecommenderSimple_df_normalized,
    FullyImplicitRecommenderSimple_online_df_normalized,
    FullyImplicitRecommenderSimple_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_df_normalized,
    FullyImplicitRecommenderWithNull_online_df_normalized,
    FullyImplicitRecommenderWithNull_online_batch_df_normalized
), axis = 0)

In [57]:
aggregat = all_results.groupby('recommendation').mean()

### Classement ratio de recommandations effectives

In [58]:
col = 'good_reco_ratio' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### Classement par average reward normalisÃ©e (max)

In [59]:
col = 'average_reward_normalized_max' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### Classement par average reward normalisÃ©e (mean)

In [65]:
col = 'average_reward_normalized_mean' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### RÃ©sumÃ© (classÃ© par average_reward)

In [63]:
cm = sns.light_palette("green", as_cmap=True)
col = 'average_reward' 
aggregat.sort_values(col, ascending=False)\
    .style.background_gradient(cmap=cm).highlight_max(color='red')

La recommendation prenant en charge les nulls semble meilleure. <br>
  1) Null secial en ligne (batch) <br>
  2) Fully Implicit Null special, en ligne (batch) <br>
  3) Null, hors ligne <br>