# Recommandation avec cold start

In [1]:
import pandas as pd

import seaborn as sns

from deep_implicit_feedback_recsys import *

from cold_star_recommender import *

from recommender_evaluation import *

Using TensorFlow backend.

In [2]:
def normalized_results(df, recommender_type):
    df['average_reward_normalized_max'] = df['average_reward'] / df['max_price']
    df['average_reward_normalized_mean'] = df['average_reward'] / df['mean_price']
    df['recommendation'] = recommender_type
    return df

In [3]:
n_loop = 5
n_pred = 100
online_batch_size = n_pred // 10
n_hidden = 1
hidden_size = 128
dropout = 0.1
l2_reg = 0

## Mesures d'Ã©chantillon

### Implicit Recommender Simple, hors ligne

In [4]:
%%time
ImplicitRecommenderSimple_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                      ImplicitRecommenderClass=ImplicitRecommenderSimple, 
                                                                      n_loop=n_loop, n_pred=n_pred,
                                                                      n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                      dropout=dropout, l2_reg=l2_reg)

CPU times: user 10.7 s, sys: 272 ms, total: 11 s
Wall time: 17.5 s

In [5]:
ImplicitRecommenderSimple_df_normalized = normalized_results(ImplicitRecommenderSimple_df, 'Simple, hors ligne')
ImplicitRecommenderSimple_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,957.110366,62.763224,210.099193,0.27,0.219514,3.347489,"Simple, hors ligne"
1,990.685893,61.664493,204.398635,0.27,0.206320,3.314689,"Simple, hors ligne"
2,974.886185,64.956995,235.849161,0.32,0.241925,3.630851,"Simple, hors ligne"
3,997.624851,70.545170,115.546526,0.30,0.115822,1.637908,"Simple, hors ligne"
4,941.617157,61.950721,77.864960,0.33,0.082693,1.256885,"Simple, hors ligne"

### Implicit Recommender Simple, en ligne

In [6]:
%%time
ImplicitRecommenderSimple_online_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=1,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 12 s, sys: 229 ms, total: 12.2 s
Wall time: 18.6 s

In [7]:
ImplicitRecommenderSimple_online_df_normalized = normalized_results(ImplicitRecommenderSimple_online_df, 'Simple, en ligne')
ImplicitRecommenderSimple_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,982.327883,68.467443,96.658036,0.33,0.098397,1.411737,"Simple, en ligne"
1,954.306026,66.852975,112.126665,0.39,0.117496,1.677213,"Simple, en ligne"
2,988.407114,74.946317,116.799601,0.31,0.118170,1.558443,"Simple, en ligne"
3,969.395533,66.352324,122.472862,0.39,0.126339,1.845796,"Simple, en ligne"
4,989.212696,74.452362,98.073555,0.36,0.099143,1.317266,"Simple, en ligne"

### Implicit Recommender Simple, en ligne version batch

In [8]:
%%time
ImplicitRecommenderSimple_online_batch_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=online_batch_size,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 13 s, sys: 189 ms, total: 13.2 s
Wall time: 18.3 s

In [9]:
ImplicitRecommenderSimple_online_batch_df_normalized = normalized_results(ImplicitRecommenderSimple_online_batch_df, 'Simple, en ligne (batch)')
ImplicitRecommenderSimple_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,995.451585,86.027852,116.211831,0.39,0.116743,1.350863,"Simple, en ligne (batch)"
1,911.568035,77.022750,249.306144,0.30,0.273492,3.236786,"Simple, en ligne (batch)"
2,955.751818,67.120421,176.448505,0.26,0.184617,2.628835,"Simple, en ligne (batch)"
3,899.991787,71.490133,108.599643,0.31,0.120667,1.519086,"Simple, en ligne (batch)"
4,999.716776,69.707068,317.077778,0.39,0.317168,4.548718,"Simple, en ligne (batch)"

### Implicit Recommender avec nuls sans indicateur, hors ligne

In [10]:
%%time
ImplicitRecommenderWithNull_no_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator, 
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 15.1 s, sys: 292 ms, total: 15.4 s
Wall time: 20.1 s

In [11]:
ImplicitRecommenderWithNull_no_indicator_df_normalized = normalized_results(ImplicitRecommenderWithNull_no_indicator_df, 'Null, hors ligne')
ImplicitRecommenderWithNull_no_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,975.511527,65.961121,283.480927,0.37,0.290597,4.297697,"Null, hors ligne"
1,922.738518,57.508824,56.297210,0.21,0.061011,0.978932,"Null, hors ligne"
2,869.342522,57.826636,347.193086,0.44,0.399374,6.004034,"Null, hors ligne"
3,987.842397,75.790264,280.645541,0.37,0.284100,3.702923,"Null, hors ligne"
4,829.516932,77.806663,119.398249,0.38,0.143937,1.534550,"Null, hors ligne"

### Implicit Recommender avec nuls sans indicateur, en ligne

In [12]:
%%time
ImplicitRecommenderWithNull_no_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 17.4 s, sys: 300 ms, total: 17.7 s
Wall time: 22 s

In [13]:
ImplicitRecommenderWithNull_no_indicator_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_no_indicator_online_df,
                                                                                   'Null, en ligne')
ImplicitRecommenderWithNull_no_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,952.446622,76.770580,200.260346,0.30,0.210259,2.608556,"Null, en ligne"
1,994.121597,61.627789,126.478123,0.40,0.127226,2.052290,"Null, en ligne"
2,963.798160,63.285135,72.477553,0.22,0.075200,1.145254,"Null, en ligne"
3,899.851847,79.651720,165.624373,0.28,0.184057,2.079357,"Null, en ligne"
4,994.805904,84.063462,241.629493,0.32,0.242891,2.874370,"Null, en ligne"

### Implicit Recommender avec nuls sans indicateur, en ligne version batch

In [14]:
%%time
ImplicitRecommenderWithNull_no_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 17.9 s, sys: 291 ms, total: 18.2 s
Wall time: 22.5 s

In [15]:
ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_no_indicator_online_batch_df, 'Null, en ligne (batch)')
ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,961.725305,84.354803,112.881001,0.33,0.117373,1.338169,"Null, en ligne (batch)"
1,926.922229,87.424844,329.660078,0.41,0.355650,3.770783,"Null, en ligne (batch)"
2,954.949844,75.217454,180.622761,0.37,0.189144,2.401341,"Null, en ligne (batch)"
3,993.149179,71.102518,128.840406,0.30,0.129729,1.812037,"Null, en ligne (batch)"
4,982.716391,75.096072,72.942228,0.19,0.074225,0.971319,"Null, en ligne (batch)"

### Implicit Recommender avec nuls et indicateur binaire, hors ligne

In [16]:
%%time
ImplicitRecommenderWithNull_binary_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 20.1 s, sys: 309 ms, total: 20.4 s
Wall time: 25 s

In [17]:
ImplicitRecommenderWithNull_binary_indicator_df_normalized = normalized_results(ImplicitRecommenderWithNull_binary_indicator_df,
                                                                                'Null binaire, hors ligne')
ImplicitRecommenderWithNull_binary_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,956.780187,73.495882,227.449202,0.27,0.237724,3.094720,"Null binaire, hors ligne"
1,914.697079,59.559191,107.936745,0.35,0.118003,1.812260,"Null binaire, hors ligne"
2,834.185051,73.025467,205.395127,0.31,0.246222,2.812651,"Null binaire, hors ligne"
3,985.803311,58.053268,86.069207,0.33,0.087309,1.482590,"Null binaire, hors ligne"
4,897.515649,75.546762,248.133330,0.36,0.276467,3.284500,"Null binaire, hors ligne"

### Implicit Recommender avec nuls et indicateur binaire, en ligne

In [18]:
%%time
ImplicitRecommenderWithNull_binary_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 21.5 s, sys: 282 ms, total: 21.8 s
Wall time: 26.3 s

In [19]:
ImplicitRecommenderWithNull_binary_indicator_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_binary_indicator_online_df,
                                                                                       'Null binaire, en ligne')
ImplicitRecommenderWithNull_binary_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,976.229958,74.320675,203.955312,0.36,0.208921,2.744261,"Null binaire, en ligne"
1,999.958321,69.340111,114.556299,0.20,0.114561,1.652093,"Null binaire, en ligne"
2,985.338568,77.709696,188.066027,0.24,0.190864,2.420110,"Null binaire, en ligne"
3,984.174280,64.678944,57.660631,0.25,0.058588,0.891490,"Null binaire, en ligne"
4,892.198806,60.225616,152.620304,0.36,0.171061,2.534143,"Null binaire, en ligne"

### Implicit Recommender avec nuls et indicateur binaire, en ligne version batch

In [20]:
%%time
ImplicitRecommenderWithNull_binary_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 22.9 s, sys: 290 ms, total: 23.2 s
Wall time: 27.6 s

In [21]:
ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_binary_indicator_online_batch_df, 'Null binaire, en ligne (batch)')
ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,953.089986,73.339743,52.012606,0.24,0.054573,0.709201,"Null binaire, en ligne (batch)"
1,932.739254,68.409529,219.921872,0.28,0.235781,3.214784,"Null binaire, en ligne (batch)"
2,951.316023,60.539077,93.591234,0.35,0.098381,1.545964,"Null binaire, en ligne (batch)"
3,938.486124,72.684545,202.767774,0.31,0.216058,2.789696,"Null binaire, en ligne (batch)"
4,979.100642,73.546661,114.494176,0.42,0.116938,1.556756,"Null binaire, en ligne (batch)"

### Implicit Recommender avec nuls et indicateur special, hors ligne

In [22]:
%%time
ImplicitRecommenderWithNull_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 24.2 s, sys: 276 ms, total: 24.4 s
Wall time: 28.8 s

In [23]:
ImplicitRecommenderWithNull_df_normalized = normalized_results(ImplicitRecommenderWithNull_df, 'Null special, hors ligne')
ImplicitRecommenderWithNull_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,925.257920,73.869558,247.201840,0.34,0.267171,3.346464,"Null special, hors ligne"
1,971.463888,77.928121,111.721364,0.30,0.115003,1.433646,"Null special, hors ligne"
2,964.598802,75.978106,88.090178,0.30,0.091323,1.159415,"Null special, hors ligne"
3,942.642999,72.091076,264.515585,0.35,0.280611,3.669186,"Null special, hors ligne"
4,899.051680,68.216977,34.658654,0.32,0.038550,0.508065,"Null special, hors ligne"

### Implicit Recommender avec nuls et indicateur special, en ligne

In [24]:
%%time
ImplicitRecommenderWithNull_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 25.8 s, sys: 340 ms, total: 26.1 s
Wall time: 31.2 s

In [25]:
ImplicitRecommenderWithNull_online_df_normalized = normalized_results(ImplicitRecommenderWithNull_online_df, 'Null special, en ligne')
ImplicitRecommenderWithNull_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,994.218553,72.432390,103.561595,0.31,0.104164,1.429769,"Null special, en ligne"
1,988.555874,82.206677,330.385164,0.36,0.334210,4.018958,"Null special, en ligne"
2,995.256813,74.818931,247.709591,0.30,0.248890,3.310788,"Null special, en ligne"
3,948.619913,80.960074,242.127159,0.29,0.255241,2.990698,"Null special, en ligne"
4,974.815009,73.229640,160.524467,0.24,0.164672,2.192070,"Null special, en ligne"

### Implicit Recommender avec nuls et indicateur special, en ligne version batch

In [26]:
%%time
ImplicitRecommenderWithNull_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 27.9 s, sys: 372 ms, total: 28.2 s
Wall time: 35.7 s

In [27]:
ImplicitRecommenderWithNull_online_batch_df_normalized = \
    normalized_results(ImplicitRecommenderWithNull_online_batch_df, 'Null special, en ligne (batch)')
ImplicitRecommenderWithNull_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,999.912726,73.474009,220.975956,0.31,0.220995,3.007539,"Null special, en ligne (batch)"
1,929.504351,66.308211,236.763549,0.32,0.254720,3.570652,"Null special, en ligne (batch)"
2,974.029690,72.510951,425.559672,0.48,0.436906,5.868902,"Null special, en ligne (batch)"
3,939.055015,80.928716,264.697959,0.35,0.281877,3.270754,"Null special, en ligne (batch)"
4,919.150479,76.197717,101.247227,0.26,0.110153,1.328744,"Null special, en ligne (batch)"

### Fully Implicit Recommender Simple, hors ligne

In [28]:
%%time
FullyImplicitRecommenderSimple_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                      ImplicitRecommenderClass=ImplicitRecommenderSimple, 
                                                                      n_loop=n_loop, n_pred=n_pred,
                                                                      n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                      dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.98 s, sys: 118 ms, total: 10.1 s
Wall time: 24.5 s

In [29]:
FullyImplicitRecommenderSimple_df_normalized = normalized_results(FullyImplicitRecommenderSimple_df, 'Fully Implicit Simple, hors ligne')
FullyImplicitRecommenderSimple_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,998.744187,87.873646,179.979184,0.26,0.180205,2.048159,"Fully Implicit Simple, hors ligne"
1,960.578581,70.397135,269.109717,0.40,0.280154,3.822737,"Fully Implicit Simple, hors ligne"
2,875.479477,70.151943,199.332850,0.39,0.227684,2.841444,"Fully Implicit Simple, hors ligne"
3,984.457383,73.571489,200.768435,0.31,0.203938,2.728889,"Fully Implicit Simple, hors ligne"
4,985.471227,68.606043,180.303177,0.35,0.182961,2.628095,"Fully Implicit Simple, hors ligne"

### Fully Implicit Recommender Simple, en ligne

In [30]:
%%time
FullyImplicitRecommenderSimple_online_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=1,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 10 s, sys: 121 ms, total: 10.2 s
Wall time: 23.2 s

In [31]:
FullyImplicitRecommenderSimple_online_df_normalized = normalized_results(FullyImplicitRecommenderSimple_online_df, 'Fully Implicit Simple, en ligne')
FullyImplicitRecommenderSimple_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,916.990841,60.738384,166.010648,0.38,0.181039,2.733208,"Fully Implicit Simple, en ligne"
1,920.412172,65.990649,159.690534,0.28,0.173499,2.419896,"Fully Implicit Simple, en ligne"
2,936.796027,71.685237,119.507929,0.24,0.127571,1.667121,"Fully Implicit Simple, en ligne"
3,946.255491,72.032511,167.438599,0.35,0.176949,2.324486,"Fully Implicit Simple, en ligne"
4,979.395693,77.595591,253.207957,0.40,0.258535,3.263175,"Fully Implicit Simple, en ligne"

### Fully Implicit Recommender Simple, en ligne version batch

In [32]:
%%time
FullyImplicitRecommenderSimple_online_batch_df = eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                                                             ImplicitRecommenderClass=ImplicitRecommenderSimple,
                                                                             n_loop=n_loop, n_pred=n_pred,
                                                                             online_batch_size=online_batch_size,
                                                                             n_hidden=n_hidden, hidden_size=hidden_size, 
                                                                             dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.82 s, sys: 105 ms, total: 9.93 s
Wall time: 19.4 s

In [33]:
FullyImplicitRecommenderSimple_online_batch_df_normalized = normalized_results(FullyImplicitRecommenderSimple_online_batch_df, 'Fully Implicit Simple, en ligne (batch)')
FullyImplicitRecommenderSimple_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,999.993906,78.947463,216.897995,0.31,0.216899,2.747371,"Fully Implicit Simple, en ligne (batch)"
1,995.041663,69.638030,178.852660,0.37,0.179744,2.568319,"Fully Implicit Simple, en ligne (batch)"
2,952.600207,58.318242,178.069478,0.39,0.186930,3.053410,"Fully Implicit Simple, en ligne (batch)"
3,998.645424,56.500697,167.051274,0.36,0.167278,2.956623,"Fully Implicit Simple, en ligne (batch)"
4,982.098423,83.883874,198.025162,0.30,0.201635,2.360706,"Fully Implicit Simple, en ligne (batch)"

### Fully Implicit Recommender avec nuls sans indicateur, hors ligne

In [34]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator, 
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 10 s, sys: 131 ms, total: 10.2 s
Wall time: 23.2 s

In [35]:
FullyImplicitRecommenderWithNull_no_indicator_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_no_indicator_df, 'Fully Implicit Null, hors ligne')
FullyImplicitRecommenderWithNull_no_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,966.012606,67.959280,123.930289,0.27,0.128291,1.823596,"Fully Implicit Null, hors ligne"
1,988.429403,80.916169,200.199398,0.30,0.202543,2.474158,"Fully Implicit Null, hors ligne"
2,970.965936,54.447156,77.735958,0.29,0.080060,1.427732,"Fully Implicit Null, hors ligne"
3,871.968819,55.506297,172.883445,0.32,0.198268,3.114664,"Fully Implicit Null, hors ligne"
4,940.419350,58.334241,117.330886,0.26,0.124764,2.011355,"Fully Implicit Null, hors ligne"

### Fully Implicit Recommender avec nuls sans indicateur, en ligne

In [36]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.71 s, sys: 116 ms, total: 9.82 s
Wall time: 16.7 s

In [37]:
FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_no_indicator_online_df,
                                                                                   'Fully Implicit Null, en ligne')
FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,972.839029,68.075048,177.009262,0.31,0.181951,2.600208,"Fully Implicit Null, en ligne"
1,991.965349,85.715320,164.237311,0.34,0.165568,1.916079,"Fully Implicit Null, en ligne"
2,995.320021,76.406964,156.693708,0.27,0.157430,2.050778,"Fully Implicit Null, en ligne"
3,952.936653,71.960183,245.069297,0.36,0.257173,3.405624,"Fully Implicit Null, en ligne"
4,956.475712,64.570148,199.984920,0.28,0.209085,3.097173,"Fully Implicit Null, en ligne"

### Fully Implicit Recommender avec nuls sans indicateur, en ligne version batch

In [38]:
%%time
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_no_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.72 s, sys: 129 ms, total: 9.85 s
Wall time: 15.1 s

In [39]:
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_no_indicator_online_batch_df, 'Fully Implicit Null, en ligne (batch)')
FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,992.104802,83.354405,248.897711,0.38,0.250878,2.986017,"Fully Implicit Null, en ligne (batch)"
1,991.265437,68.515937,141.333628,0.32,0.142579,2.062785,"Fully Implicit Null, en ligne (batch)"
2,985.924658,83.468276,149.498276,0.24,0.151633,1.791079,"Fully Implicit Null, en ligne (batch)"
3,949.989963,69.301113,167.994335,0.37,0.176838,2.424122,"Fully Implicit Null, en ligne (batch)"
4,989.203472,72.410015,215.530418,0.33,0.217883,2.976528,"Fully Implicit Null, en ligne (batch)"

### Fully Implicit Recommender avec nuls et indicateur binaire, hors ligne

In [40]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.52 s, sys: 96.4 ms, total: 9.61 s
Wall time: 14.7 s

In [41]:
FullyImplicitRecommenderWithNull_binary_indicator_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_df,
                                                                                'Fully Implicit Null binaire, hors ligne')
FullyImplicitRecommenderWithNull_binary_indicator_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,953.865219,68.334985,161.092487,0.33,0.168884,2.357394,"Fully Implicit Null binaire, hors ligne"
1,975.370424,62.779510,199.837050,0.34,0.204883,3.183157,"Fully Implicit Null binaire, hors ligne"
2,987.237849,68.412168,250.774689,0.38,0.254016,3.665645,"Fully Implicit Null binaire, hors ligne"
3,977.081632,76.836237,217.389148,0.33,0.222488,2.829253,"Fully Implicit Null binaire, hors ligne"
4,901.490438,61.525290,147.544439,0.32,0.163667,2.398110,"Fully Implicit Null binaire, hors ligne"

### Fully Implicit Recommender avec nuls et indicateur binaire, en ligne

In [42]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.53 s, sys: 104 ms, total: 9.64 s
Wall time: 15.2 s

In [43]:
FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_online_df,
                                                                                       'Fully Implicit Null binaire, en ligne')
FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,978.273272,65.392643,152.857494,0.31,0.156252,2.337533,"Fully Implicit Null binaire, en ligne"
1,988.709090,73.183640,160.946144,0.26,0.162784,2.199209,"Fully Implicit Null binaire, en ligne"
2,981.011386,80.012973,218.249198,0.34,0.222474,2.727673,"Fully Implicit Null binaire, en ligne"
3,990.074495,72.388248,192.841681,0.30,0.194775,2.663992,"Fully Implicit Null binaire, en ligne"
4,902.725823,80.976504,207.688469,0.31,0.230068,2.564799,"Fully Implicit Null binaire, en ligne"

### Fully Implicit Recommender avec nuls et indicateur binaire, en ligne version batch

In [44]:
%%time
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull_binary_indicator,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.82 s, sys: 104 ms, total: 9.92 s
Wall time: 15.2 s

In [45]:
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df, 'Fully Implicit Null binaire, en ligne (batch)')
FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,984.212291,66.361736,163.922492,0.33,0.166552,2.470136,"Fully Implicit Null binaire, en ligne (batch)"
1,990.377788,79.426773,123.592648,0.27,0.124793,1.556058,"Fully Implicit Null binaire, en ligne (batch)"
2,998.285319,70.127566,172.934852,0.28,0.173232,2.466004,"Fully Implicit Null binaire, en ligne (batch)"
3,973.372095,88.906672,266.338381,0.36,0.273624,2.995707,"Fully Implicit Null binaire, en ligne (batch)"
4,985.394497,62.489006,122.542112,0.27,0.124358,1.961019,"Fully Implicit Null binaire, en ligne (batch)"

### Fully Implicit Recommender avec nuls et indicateur special, hors ligne

In [46]:
%%time
FullyImplicitRecommenderWithNull_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 10.2 s, sys: 117 ms, total: 10.3 s
Wall time: 17.1 s

In [47]:
FullyImplicitRecommenderWithNull_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_df, 'Fully Implicit Null special, hors ligne')
FullyImplicitRecommenderWithNull_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,984.400208,58.855992,139.804788,0.28,0.142020,2.375370,"Fully Implicit Null special, hors ligne"
1,956.124277,68.059714,223.105213,0.39,0.233343,3.278080,"Fully Implicit Null special, hors ligne"
2,969.619056,57.321907,124.141009,0.31,0.128031,2.165682,"Fully Implicit Null special, hors ligne"
3,976.745968,79.288430,245.851180,0.34,0.251704,3.100719,"Fully Implicit Null special, hors ligne"
4,993.267157,65.303432,172.249610,0.27,0.173417,2.637681,"Fully Implicit Null special, hors ligne"

### Fully Implicit Recommender avec nuls et indicateur special, en ligne

In [48]:
%%time
FullyImplicitRecommenderWithNull_online_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=1,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 9.83 s, sys: 119 ms, total: 9.95 s
Wall time: 21.9 s

In [49]:
FullyImplicitRecommenderWithNull_online_df_normalized = normalized_results(FullyImplicitRecommenderWithNull_online_df, 'Fully Implicit Null special, en ligne')
FullyImplicitRecommenderWithNull_online_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,996.981748,71.871103,176.276558,0.30,0.176810,2.452676,"Fully Implicit Null special, en ligne"
1,966.726054,88.548382,335.111007,0.42,0.346645,3.784496,"Fully Implicit Null special, en ligne"
2,965.678120,69.548682,215.605625,0.34,0.223269,3.100068,"Fully Implicit Null special, en ligne"
3,959.102922,84.402868,196.682358,0.31,0.205069,2.330280,"Fully Implicit Null special, en ligne"
4,993.006701,71.980422,136.962843,0.28,0.137927,1.902779,"Fully Implicit Null special, en ligne"

### Fully Implicit Recommender avec nuls et indicateur special, en ligne version batch

In [50]:
%%time
FullyImplicitRecommenderWithNull_online_batch_df = \
    eval_loop_ColdStartImplicitRecommender(ColdStartRecommenderClass=ColdStartFullyImplicitRecommender,
                                           ImplicitRecommenderClass=ImplicitRecommenderWithNull,
                                           n_loop=n_loop, n_pred=n_pred,
                                           online_batch_size=online_batch_size,
                                           n_hidden=n_hidden, hidden_size=hidden_size, 
                                           dropout=dropout, l2_reg=l2_reg)

CPU times: user 10.4 s, sys: 104 ms, total: 10.5 s
Wall time: 17.3 s

In [51]:
FullyImplicitRecommenderWithNull_online_batch_df_normalized = \
    normalized_results(FullyImplicitRecommenderWithNull_online_batch_df, 'Fully Implicit Null special, en ligne (batch)')
FullyImplicitRecommenderWithNull_online_batch_df_normalized

,max_price,mean_price,average_reward,good_reco_ratio,average_reward_normalized_max,average_reward_normalized_mean,recommendation
0,979.424276,70.813250,280.981377,0.47,0.286884,3.967921,"Fully Implicit Null special, en ligne (batch)"
1,992.961454,72.954070,240.318119,0.41,0.242022,3.294102,"Fully Implicit Null special, en ligne (batch)"
2,964.619998,72.676680,170.164508,0.28,0.176406,2.341391,"Fully Implicit Null special, en ligne (batch)"
3,995.838606,76.023025,224.828480,0.35,0.225768,2.957374,"Fully Implicit Null special, en ligne (batch)"
4,971.367305,70.043967,176.972520,0.35,0.182189,2.526592,"Fully Implicit Null special, en ligne (batch)"

## Aggregation des rÃ©sutats

In [52]:
all_results = pd.concat( (
    ImplicitRecommenderSimple_df_normalized,
    ImplicitRecommenderSimple_online_df_normalized,
    ImplicitRecommenderSimple_online_batch_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_online_df_normalized,
    ImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_online_df_normalized,
    ImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized,
    ImplicitRecommenderWithNull_df_normalized,
    ImplicitRecommenderWithNull_online_df_normalized,
    ImplicitRecommenderWithNull_online_batch_df_normalized,
    
    FullyImplicitRecommenderSimple_df_normalized,
    FullyImplicitRecommenderSimple_online_df_normalized,
    FullyImplicitRecommenderSimple_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_online_df_normalized,
    FullyImplicitRecommenderWithNull_no_indicator_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_online_df_normalized,
    FullyImplicitRecommenderWithNull_binary_indicator_online_batch_df_normalized,
    FullyImplicitRecommenderWithNull_df_normalized,
    FullyImplicitRecommenderWithNull_online_df_normalized,
    FullyImplicitRecommenderWithNull_online_batch_df_normalized
), axis = 0)

In [53]:
aggregat = all_results.groupby('recommendation').mean()

### Classement ratio de recommandations effectives

In [54]:
col = 'good_reco_ratio' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### Classement par average reward normalisÃ©e (max)

In [55]:
col = 'average_reward_normalized_max' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### Classement par average reward normalisÃ©e (mean)

In [56]:
col = 'average_reward_normalized_mean' 
aggregat.sort_values(col, ascending=False)\
    .style.apply((lambda x: ['background: lightgreen' if x.name == col else '' for _ in x]))

### RÃ©sumÃ© (classÃ© par average_reward)

In [57]:
cm = sns.light_palette("green", as_cmap=True)
col = 'average_reward' 
aggregat.sort_values(col, ascending=False)\
    .style.background_gradient(cmap=cm)

La recommendation prenant en charge les nulls semble meilleure. <br>
  1) Null hors ligne <br>
  2) Null en ligne <br>
  3) Null special, en ligne (batch) <br>